#!/bin/sh
# --------
# returns the system name .
# Anyone has a BETTER Idea?
# --------
sys=`uname -s`
case $sys in
  "HPUX") 
	echo "HPUX"
	;;
  "OSF1")
	 echo "OSF1"
	;;
  "SunOS") 
        version=`uname -r`
        part1=`expr "$version" : "\([0-9][0-9]*\)"`
	if [ $part1 -ge 5 ];  then
		echo "SOLARIS" 
	else
		echo "SUNOS"
	fi 
	;;
   *)
        echo $sys
	;;
esac

