; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Uplink
AppVerName=Uplink v1.31
AppPublisher=Introversion Software Ltd
Compression=zip/5
DefaultDirName={pf}\Uplink
DefaultGroupName=Uplink
LicenseFile=c:\development\Uplink\tools\IntroversionEULA.txt
OutputBaseFilename=setup

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone

[Files]
Source: "..\build\data.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\fonts.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\graphics.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\loading.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\music.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\patch.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\sounds.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\world.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\readme.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\changes.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\glu32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\glut32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\tcp4w32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\uplink.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Uplink"; Filename: "{app}\uplink.exe"; WorkingDir: "{app}"
Name: "{group}\Uplink Website"; Filename: "http://www.uplink.co.uk"
Name: "{group}\Readme"; Filename: "{app}\readme.txt"
Name: "{group}\Introversion Website"; Filename: "http://www.introversion.co.uk"
Name: "{group}\{cm:UninstallProgram,Uplink}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Uplink"; Filename: "{app}\uplink.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[UninstallDelete]
Type: files; Name: "{app}\uplink.url"
Type: filesandordirs; Name: "{app}\users"
Type: filesandordirs; Name: "{app}\temp"

